### ISSUE TITLE
Test suite failure on hydra

### ISSUE THREAD

**Issue by PierreR** [ajnsit/luautils#4]
http://hydra.cryp.to/build/956863#tabs-summary

**Comment by ajnsit** [comment]
Thanks for reporting this! Looks like a bug in HsLua. I'll file a report.

**Comment by ajnsit** [comment]
I've opened up a pull request here - https://github.com/osa1/hslua/pull/30

**Comment by ajnsit** [comment]
Meanwhile I have removed the offending test case from the test suite. It anyways tested functionality that is now a part of HsLua and should probably be a part of HsLua's test suite.

**Comment by ajnsit** [comment]
The bug has been fixed in HsLua. Closing this issue.
